name: Magnet to Google Drive

on:
  workflow_dispatch:
    inputs:
      magnet:
        description: "Magnet link"
        required: true
        type: string
      chat_id:
        description: "Telegram chat ID"
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: |
          echo "MAGNET RECEIVED"
          echo "Chat ID: ${{ inputs.chat_id }}"
          echo "Magnet length: ${#MAGNET}"
        env:
          MAGNET: ${{ inputs.magnet }}
